# Generated by Django 5.0.6 on 2024-10-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='a',
            new_name='cantidad',
        ),
    ]
