# Generated by Django 5.0.6 on 2024-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidadVentas',
            field=models.IntegerField(default=0),
        ),
    ]
